#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# e2e is included so new Playwright specs cannot ship without a header. RAT now covers e2e/
# as well, so this is a second, independent check rather than the only one.
#
# The header is verified in three places, not one. Six e2e specs once shipped with a header
# whose body had been spliced -- "with the License.  See the NOTICE file BASIS, WITHOUT" --
# losing the grant sentence, the licence URL and the "AS IS" clause. It still opened with the
# ASF phrase, so a check that looked only for that phrase passed all six.
FILES=$(find src deploy .github scripts e2e -type f \( -name "*.ts" -o -name "*.html" -o -name "*.scss" -o -name "*.yml" -o -name "*.sh" -o -name "Dockerfile" -o -name "nginx.conf" -o -name "nginx.conf.template" -o -name "eslint.config.js" -o -name ".prettierignore" \) -not -path "src/app/api/*")

MISSING_HEADERS=0

for FILE in $FILES; do
  if [ ! -f "$FILE" ]; then
    continue
  fi

  if ! grep -q "Licensed to the Apache Software Foundation" "$FILE"; then
    echo "Missing Apache License header in $FILE"
    MISSING_HEADERS=$((MISSING_HEADERS + 1))
  elif ! grep -q "http://www.apache.org/licenses/LICENSE-2.0" "$FILE"; then
    echo "Incomplete Apache License header (no licence URL) in $FILE"
    MISSING_HEADERS=$((MISSING_HEADERS + 1))
  elif ! grep -q "AS IS\" BASIS" "$FILE"; then
    echo "Incomplete Apache License header (no \"AS IS\" clause) in $FILE"
    MISSING_HEADERS=$((MISSING_HEADERS + 1))
  fi
done

# eslint-suppressions.json is generated by `eslint --suppress-all` and rewritten by
# --prune-suppressions. JSON has no comment syntax, and any license key added by hand would
# be data ESLint overwrites on the next run, so there is nowhere for the field to live.
JSON_FILES=$(find . -maxdepth 1 -name "*.json" ! -name "package-lock.json" ! -name "angular.json" ! -name "playwright-results.json" ! -name "eslint-suppressions.json")
JSON_FILES="$JSON_FILES $(find src/assets/i18n -name "*.json")"
JSON_FILES="$JSON_FILES .asf.yaml"

for FILE in $JSON_FILES; do
  if [ ! -f "$FILE" ]; then
    continue
  fi
  if [[ "$FILE" == *".asf.yaml" ]]; then
    continue
  fi
  if ! grep -i -q "Apache-2.0" "$FILE" && ! grep -q "Apache License" "$FILE"; then
    echo "Missing Apache license reference in $FILE"
    MISSING_HEADERS=$((MISSING_HEADERS + 1))
  fi
done

# ASF release policy requires both files in every distribution. The repository had no NOTICE
# at all until this was added, and no check would have noticed.
for REQUIRED in LICENSE NOTICE; do
  if [ ! -f "$REQUIRED" ]; then
    echo "Required ASF file missing from the repository root: $REQUIRED"
    MISSING_HEADERS=$((MISSING_HEADERS + 1))
  fi
done

if [ $MISSING_HEADERS -gt 0 ]; then
  echo "Found $MISSING_HEADERS files missing license headers/fields."
  exit 1
else
  echo "All checked files have license headers/fields."
  exit 0
fi
