/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import {
  addCircleOutline,
  addOutline,
  alertCircleOutline,
  analyticsOutline,
  arrowBackOutline,
  arrowDownOutline,
  arrowUndoOutline,
  arrowUpOutline,
  attachOutline,
  barChartOutline,
  bookOutline,
  buildOutline,
  businessOutline,
  calculatorOutline,
  calendarClearOutline,
  calendarNumberOutline,
  calendarOutline,
  cardOutline,
  caretDownOutline,
  cashOutline,
  chatbubbleOutline,
  checkboxOutline,
  checkmarkCircleOutline,
  checkmarkDoneOutline,
  checkmarkOutline,
  chevronBackOutline,
  chevronForwardOutline,
  clipboardOutline,
  closeCircleOutline,
  closeOutline,
  cloudOutline,
  cloudUploadOutline,
  codeSlashOutline,
  compassOutline,
  constructOutline,
  createOutline,
  cubeOutline,
  documentTextOutline,
  downloadOutline,
  ellipsisVerticalOutline,
  eyeOutline,
  fileTrayOutline,
  filterOutline,
  flagOutline,
  flashOutline,
  gitCommitOutline,
  gitNetworkOutline,
  gitCompareOutline,
  gridOutline,
  hammerOutline,
  hardwareChipOutline,
  helpCircleOutline,
  idCardOutline,
  informationCircleOutline,
  keyOutline,
  layersOutline,
  linkOutline,
  listOutline,
  locationOutline,
  lockClosedOutline,
  lockOpenOutline,
  mailOpenOutline,
  mailOutline,
  megaphoneOutline,
  menuOutline,
  moonOutline,
  notificationsOutline,
  openOutline,
  optionsOutline,
  paperPlaneOutline,
  pauseCircleOutline,
  personRemoveOutline,
  pauseOutline,
  peopleCircleOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  personOutline,
  pieChartOutline,
  playCircleOutline,
  playForwardOutline,
  playOutline,
  playSkipBackOutline,
  playSkipForwardOutline,
  powerOutline,
  pricetagsOutline,
  pulseOutline,
  receiptOutline,
  refreshCircleOutline,
  refreshOutline,
  removeCircleOutline,
  removeOutline,
  repeatOutline,
  ribbonOutline,
  saveOutline,
  searchCircleOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  shieldOutline,
  giftOutline,
  arrowDownCircleOutline,
  arrowUpCircleOutline,
  pricetagOutline,
  returnDownBackOutline,
  storefrontOutline,
  sunnyOutline,
  swapHorizontalOutline,
  timeOutline,
  todayOutline,
  trashBinOutline,
  trashOutline,
  trendingDownOutline,
  trendingUpOutline,
  unlinkOutline,
  walletOutline,
  warningOutline,
} from 'ionicons/icons';

/**
 * Every ionicon rendered anywhere in the application.
 *
 * Ionic resolves <ion-icon name="..."> by lazily fetching an SVG unless the icon has been
 * registered up front. Registering the full set once at bootstrap keeps icons working offline
 * and removes the need to copy the ionicons SVGs into the build assets.
 *
 * Keys are the kebab-case names used in templates; keep this list in sync when adding icons.
 */
export const APP_ICONS: Record<string, string> = {
  'add-circle-outline': addCircleOutline,
  'add-outline': addOutline,
  'alert-circle-outline': alertCircleOutline,
  'analytics-outline': analyticsOutline,
  'arrow-back-outline': arrowBackOutline,
  'arrow-down-outline': arrowDownOutline,
  'arrow-undo-outline': arrowUndoOutline,
  'arrow-up-outline': arrowUpOutline,
  'attach-outline': attachOutline,
  'bar-chart-outline': barChartOutline,
  'book-outline': bookOutline,
  'build-outline': buildOutline,
  'business-outline': businessOutline,
  'calculator-outline': calculatorOutline,
  'calendar-clear-outline': calendarClearOutline,
  'calendar-number-outline': calendarNumberOutline,
  'calendar-outline': calendarOutline,
  'card-outline': cardOutline,
  'caret-down-outline': caretDownOutline,
  'cash-outline': cashOutline,
  'chatbubble-outline': chatbubbleOutline,
  'checkbox-outline': checkboxOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
  'checkmark-outline': checkmarkOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'clipboard-outline': clipboardOutline,
  'close-circle-outline': closeCircleOutline,
  'close-outline': closeOutline,
  'cloud-outline': cloudOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'code-slash-outline': codeSlashOutline,
  'compass-outline': compassOutline,
  'construct-outline': constructOutline,
  'create-outline': createOutline,
  'cube-outline': cubeOutline,
  'document-text-outline': documentTextOutline,
  'download-outline': downloadOutline,
  'ellipsis-vertical-outline': ellipsisVerticalOutline,
  'eye-outline': eyeOutline,
  'file-tray-outline': fileTrayOutline,
  'filter-outline': filterOutline,
  'flag-outline': flagOutline,
  'flash-outline': flashOutline,
  'git-commit-outline': gitCommitOutline,
  'git-network-outline': gitNetworkOutline,
  'git-compare-outline': gitCompareOutline,
  'grid-outline': gridOutline,
  'hammer-outline': hammerOutline,
  'hardware-chip-outline': hardwareChipOutline,
  'help-circle-outline': helpCircleOutline,
  'id-card-outline': idCardOutline,
  'information-circle-outline': informationCircleOutline,
  'key-outline': keyOutline,
  'layers-outline': layersOutline,
  'link-outline': linkOutline,
  'list-outline': listOutline,
  'location-outline': locationOutline,
  'lock-closed-outline': lockClosedOutline,
  'lock-open-outline': lockOpenOutline,
  'mail-open-outline': mailOpenOutline,
  'mail-outline': mailOutline,
  'megaphone-outline': megaphoneOutline,
  'menu-outline': menuOutline,
  'moon-outline': moonOutline,
  'notifications-outline': notificationsOutline,
  'open-outline': openOutline,
  'options-outline': optionsOutline,
  'paper-plane-outline': paperPlaneOutline,
  'pause-outline': pauseOutline,
  'people-circle-outline': peopleCircleOutline,
  'people-outline': peopleOutline,
  'person-add-outline': personAddOutline,
  'person-circle-outline': personCircleOutline,
  'person-outline': personOutline,
  'pie-chart-outline': pieChartOutline,
  'play-circle-outline': playCircleOutline,
  'play-forward-outline': playForwardOutline,
  'play-outline': playOutline,
  'play-skip-back-outline': playSkipBackOutline,
  'play-skip-forward-outline': playSkipForwardOutline,
  'power-outline': powerOutline,
  'pricetags-outline': pricetagsOutline,
  'pulse-outline': pulseOutline,
  'receipt-outline': receiptOutline,
  'refresh-circle-outline': refreshCircleOutline,
  'refresh-outline': refreshOutline,
  'remove-circle-outline': removeCircleOutline,
  'remove-outline': removeOutline,
  'repeat-outline': repeatOutline,
  'ribbon-outline': ribbonOutline,
  'save-outline': saveOutline,
  'search-circle-outline': searchCircleOutline,
  'search-outline': searchOutline,
  'settings-outline': settingsOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'shield-outline': shieldOutline,
  'gift-outline': giftOutline,
  'arrow-down-circle-outline': arrowDownCircleOutline,
  'arrow-up-circle-outline': arrowUpCircleOutline,
  'pause-circle-outline': pauseCircleOutline,
  'person-remove-outline': personRemoveOutline,
  'pricetag-outline': pricetagOutline,
  'return-down-back-outline': returnDownBackOutline,
  'storefront-outline': storefrontOutline,
  'sunny-outline': sunnyOutline,
  'swap-horizontal-outline': swapHorizontalOutline,
  'time-outline': timeOutline,
  'today-outline': todayOutline,
  'trash-bin-outline': trashBinOutline,
  'trash-outline': trashOutline,
  'trending-down-outline': trendingDownOutline,
  'trending-up-outline': trendingUpOutline,
  'unlink-outline': unlinkOutline,
  'wallet-outline': walletOutline,
  'warning-outline': warningOutline,
};
